package conversiones;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Osmar Daniel Morales Carballo
 */
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
public class Practica_2_0 extends javax.swing.JFrame {

    /**
     * Creates new form Practica_2_0
     */
    public Practica_2_0() {
        initComponents();
        setSize(590, 430); // tamaño de la ventana
        setLocationRelativeTo(null); // centrar en pantalla
        setResizable(false); // evitar que se pueda cambiar tamaño
    }
    //metodo para mostrar los datos en la tabla
    void mostrarDatos(){
    String columnas[] = {"ID", "Valor", "Resultado", "Tipo"};
    DefaultTableModel modelo = new DefaultTableModel(null, columnas);

    tblDatos.setModel(modelo);
//codigo sql para mostrar toda la informacion de la tabla conversiones
    String sql = "SELECT * FROM conversiones";

    try {
        //llama a una conexion en otra clase parta poder insertar los valores en la base de datos
        conexion conector = new conexion();
        Connection con = conector.getConexion();
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(sql);

        while(rs.next()){
            String fila[] = new String[4];
            fila[0] = rs.getString("id_conversion");
            fila[1] = rs.getString("valor_ingresado");
            fila[2] = rs.getString("resultado");
            fila[3] = rs.getString("tipo_de_conversion");

            modelo.addRow(fila);
        }

        con.close();

    } catch(Exception e){
        //en caso de error muestra un mensaje de que fallo la conexion
        JOptionPane.showMessageDialog(this, "Error al mostrar: " + e.getMessage());
    }
}
    //metodo para guardar los datos en la base de datos
void guardarDatos(double valor, double resultado, String tipo){
    try {
        //llama a una conexion de otra clase
        conexion conector = new conexion();
        Connection con = conector.getConexion();
//codigo sql para poder insertar los datos en la tabla
        String sql = "INSERT INTO conversiones (valor_ingresado, resultado, tipo_de_conversion) VALUES (?,?,?)";
        PreparedStatement ps = con.prepareStatement(sql);

        ps.setDouble(1, valor);
        ps.setDouble(2, resultado);
        ps.setString(3, tipo);

        ps.executeUpdate();
        con.close();

    } catch(Exception e){
        //en caso de fallar la conexion muestra un mensaje de error
        JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblError = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtValores = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnAlmacenados = new javax.swing.JButton();
        btnFahrenheit1 = new javax.swing.JButton();
        btnCentigrados1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        btnBorrar1 = new javax.swing.JButton();
        JScrollPane = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        lblError.setForeground(new java.awt.Color(255, 51, 0));
        getContentPane().add(lblError, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel2.setText("Conversion de temperaturas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Resultado:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 90, -1));

        txtValores.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtValores.setForeground(new java.awt.Color(204, 204, 204));
        txtValores.setText("Ingrese la cantidad");
        txtValores.setBorder(null);
        txtValores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtValoresMousePressed(evt);
            }
        });
        txtValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValoresActionPerformed(evt);
            }
        });
        jPanel1.add(txtValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 206, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 357, 10));

        btnAlmacenados.setBackground(new java.awt.Color(0, 51, 153));
        btnAlmacenados.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAlmacenados.setForeground(new java.awt.Color(255, 255, 255));
        btnAlmacenados.setText("Mostrar datos");
        btnAlmacenados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlmacenados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlmacenadosActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlmacenados, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 110, 40));

        btnFahrenheit1.setBackground(new java.awt.Color(0, 51, 153));
        btnFahrenheit1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnFahrenheit1.setForeground(new java.awt.Color(255, 255, 255));
        btnFahrenheit1.setText("Fahrenheit");
        btnFahrenheit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFahrenheit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFahrenheit1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnFahrenheit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 110, 40));

        btnCentigrados1.setBackground(new java.awt.Color(0, 51, 153));
        btnCentigrados1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCentigrados1.setForeground(new java.awt.Color(255, 255, 255));
        btnCentigrados1.setText("Centigrados");
        btnCentigrados1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCentigrados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCentigrados1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCentigrados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 110, 40));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Datos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 37, -1));

        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado.setText("________________________");
        jPanel1.add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 170, 30));

        btnBorrar1.setBackground(new java.awt.Color(0, 51, 153));
        btnBorrar1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBorrar1.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar1.setText("Borrar");
        btnBorrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 110, 40));

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Valor", "Resultado", "Tipo"
            }
        ));
        tblDatos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        JScrollPane.setViewportView(tblDatos);

        jPanel1.add(JScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 310, 110));

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValoresActionPerformed
        
    }//GEN-LAST:event_txtValoresActionPerformed

    private void txtValoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtValoresMousePressed
        txtValores.setText("");
        txtValores.setForeground(Color.black);
    }//GEN-LAST:event_txtValoresMousePressed

    //Código para el boton de "Borrar"
    private void btnAlmacenadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlmacenadosActionPerformed
    //Comandos para mostrar los valores de los campos:
    mostrarDatos();

    }//GEN-LAST:event_btnAlmacenadosActionPerformed

    //Código para el boton de "Fahrenheit"
    private void btnFahrenheit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFahrenheit1ActionPerformed
         try {
             //realiza las operaciones segun el boton seleccionado
        double v1, farh1;

        v1 = Double.parseDouble(txtValores.getText());
        farh1 = v1 * (9.0 / 5.0) + 32;

        lblResultado.setText(String.format("%.2f Fahrenheit", farh1));
        lblError.setText("");
//le da la informacion al campo de que tipo de conversion fue
        guardarDatos(v1, farh1, "C a F");

    } catch (NumberFormatException e) {
        //en caso de que el usuario escriba algun otro dato que no sea numerico salta este mensaje de error
        JOptionPane.showMessageDialog(this, "Solo se permiten valores numéricos");
    }    
    }//GEN-LAST:event_btnFahrenheit1ActionPerformed

    //Código para el boton de "Centigrados"
    private void btnCentigrados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentigrados1ActionPerformed
                                                    
    try {
        //realiza las operaciones segun los valores dados y el boton seleccionado
        double v1, cent1;

        v1 = Double.parseDouble(txtValores.getText());
        cent1 = (v1 - 32) * (5.0 / 9.0);

        lblResultado.setText(String.format("%.2f Centigrados", cent1));
        lblError.setText("");
//da la informacion para guardarla en la base de datos
        guardarDatos(v1, cent1, "F a C");

    } catch(NumberFormatException e){
        //en caso de que se escriba algun otro dato que no sea numerico salta un mensaje de error
        JOptionPane.showMessageDialog(this, "Solo se permiten valores numericos.");
    }

    }//GEN-LAST:event_btnCentigrados1ActionPerformed

    private void btnBorrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar1ActionPerformed
    //borra los valores ingresados
    txtValores.requestFocus();
        txtValores.setText("");
    lblResultado.setText("");
    }//GEN-LAST:event_btnBorrar1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //regresa al menu principal cerrando el programa
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practica_2_0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practica_2_0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practica_2_0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practica_2_0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica_2_0().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane;
    private javax.swing.JButton btnAlmacenados;
    private javax.swing.JButton btnBorrar1;
    private javax.swing.JButton btnCentigrados1;
    private javax.swing.JButton btnFahrenheit1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtValores;
    // End of variables declaration//GEN-END:variables
}
