package pagoempleados;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author terey
 */
public class PagoDeEmpleados extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PagoDeEmpleados.class.getName());

    /**
     * Creates new form PagoDeEmpleados
     */
    public PagoDeEmpleados() {
        initComponents();
        setLocationRelativeTo(null); // centrar en pantalla
        setResizable(false); // evitar que se pueda cambiar tamaño
        setSize(400, 550); // tamaño de la ventana
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEmpleado = new javax.swing.JTextField();
        txtHoras = new javax.swing.JTextField();
        txtTarifa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtR = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtRegresar = new javax.swing.JButton();
        JScrollPane = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setText("PAGO DE EMPLEADOS");

        jLabel2.setText("EMPLEADO");

        jLabel3.setText("HORAS");

        jLabel4.setText("TARIFA");

        txtEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpleadoActionPerformed(evt);
            }
        });

        txtR.setColumns(20);
        txtR.setRows(5);
        jScrollPane1.setViewportView(txtR);

        jButton1.setText("MOSTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("LIMPIAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtRegresar.setText("REGRESAR");
        txtRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegresarActionPerformed(evt);
            }
        });

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "nombre", "horas", "tarifa", "basico", "bonificacion", "neto"
            }
        ));
        JScrollPane.setViewportView(tblDatos);

        jButton3.setText("MOSTRAR DATOS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addGap(30, 30, 30)
                                                    .addComponent(jButton1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jButton2))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(23, 23, 23)
                                                    .addComponent(txtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(27, 27, 27)
                                                    .addComponent(jLabel4)))
                                            .addGap(27, 27, 27)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtRegresar)))))))
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(txtRegresar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 415, 480);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpleadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//Entrada
//realiza la conexion con la base de datos
try{
      Connection conexion;
            String dbuser ="root"; // Usuario MySQL
            String dbpassw = "zeusonario"; //Contraseña del mySQL
            String databasename ="programas"; //nombre de la db
            String url ="jdbc:mysql://localhost:3306/" + databasename;
            
            //Sentencia SQL con parametros
            String sql;
            sql = "INSERT INTO empleados(nombre_empleado, horas, tarifa, basico, bonificacion, neto)";
            sql += "VALUES (?,?,?,?,?,?)";
            
            // Lectura de datos del formulario
            String Empleado = txtEmpleado.getText();
            int horas = Integer.parseInt(txtHoras.getText());
            double tarifa = Double.parseDouble(txtTarifa.getText());
            
            //Calculos 
            double basico = horas * tarifa;
            double bonificacion = basico *0.2;
            double neto = (basico + bonificacion) * 0.9;
            
            String.format("%.3f", neto);
             String.format("%.3f", tarifa);
             
             //Mostrar resultados en el text area
            txtR.setText("Resumen de pago de Empleados\n");
            txtR.append("\nEl empleado: " + Empleado);
            txtR.append("\nEl basico es " + basico);
            txtR.append("\nLa bonificación es " + bonificacion);
            txtR.append("\nEl neto es: " + neto);
            
            //Insertar en la base de datos
            try {
                Class.forName("com.mysql.cj.jdbc.Driver"); //cargar el driver
                conexion = DriverManager.getConnection(url, dbuser, dbpassw);
                
                PreparedStatement pstm;
                pstm = (PreparedStatement) conexion.prepareStatement(sql);
                
                pstm.setString(1, Empleado);
                pstm.setInt(2, horas);
                pstm.setDouble(3, tarifa);
                pstm.setDouble(4, basico);
                pstm.setDouble(5, bonificacion);
                pstm.setDouble(6, neto);
                
                int rtdo = pstm.executeUpdate();
                
                if (rtdo == 1)
                    JOptionPane.showMessageDialog(this, "Fila correctamemnte insertada");
                else
                    throw new RuntimeException("No se pudo insertar la fila");
            }catch (ClassNotFoundException | RuntimeException | SQLException e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Conexion fallida");
                throw new RuntimeException(e);
            }
            
    }//GEN-LAST:event_jButton1ActionPerformed
    catch (Exception e){
        javax.swing.JOptionPane.showMessageDialog(this, "Ingresa datos validos (numeros)");
    }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//borra todos los valores ingresados en los cuadros de texto y de la lista
        txtEmpleado.setText("");
    txtHoras.setText("");
    txtTarifa.setText("");
    txtR.setText("");
    txtEmpleado.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegresarActionPerformed
this.dispose();        // PARA REGRESAR AL MENU
    }//GEN-LAST:event_txtRegresarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      //realiza la conexion con la base de datos para poder mostrar los datos
        Connection conexion;
    String dbuser ="root";
    String dbpassw = "zeusonario";
    String databasename ="programas";
    String url ="jdbc:mysql://localhost:3306/" + databasename;

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        conexion = DriverManager.getConnection(url, dbuser, dbpassw);
//codigo sql para que poder mostrar toda la informacion de la tabla empleados
        String sql = "SELECT * FROM empleados";
        PreparedStatement ps = conexion.prepareStatement(sql);
        java.sql.ResultSet rs = ps.executeQuery();

        // modelo de la tabla
        javax.swing.table.DefaultTableModel modelo = 
            (javax.swing.table.DefaultTableModel) tblDatos.getModel();

        // limpia tabla antes de cargar
        modelo.setRowCount(0);

        // Recorrer resultados
        while (rs.next()) {
            Object[] fila = new Object[7];
            //recopila los valores de cada campo y los muestra en la columna correspondiente
            fila[0] = rs.getInt("id_empleado"); 
            fila[1] = rs.getString("nombre_empleado");
            fila[2] = rs.getInt("horas");
            fila[3] = rs.getDouble("tarifa");
            fila[4] = rs.getDouble("basico");
            fila[5] = rs.getDouble("bonificacion");
            fila[6] = rs.getDouble("neto");

            modelo.addRow(fila);
        }

    } catch (Exception e) {
        //en caso de algun error con la conexion al mostrar salta un mensaje de error
        JOptionPane.showMessageDialog(this, "Error al mostrar datos");
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PagoDeEmpleados().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtEmpleado;
    private javax.swing.JTextField txtHoras;
    private javax.swing.JTextArea txtR;
    private javax.swing.JButton txtRegresar;
    private javax.swing.JTextField txtTarifa;
    // End of variables declaration//GEN-END:variables
}